pekko {
  actor {
    provider = "cluster"
    serialization-bindings {
      "it.unibo.alarm.cluster.CborSerializable" = jackson-cbor
    }
  }

  remote.artery {
    canonical {
      hostname = "127.0.0.1"
      port = 2551
    }
  }

  cluster {
    seed-nodes = [
      "pekko://AlarmCluster@127.0.0.1:2551"
    ]

    roles = ["worker-node"]

    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"

    sharding {
      # The extension creates a so called coordinator that manages the distribution of shards.
      # By default it runs as a Cluster Singleton.
      # Setting this to ensure idle entities are passivated after a while to save memory.
      passivation {
        default-idle-strategy {
          idle-entity.timeout = 2 minutes
        }
      }
    }
  }
}