name: Build LaTeX Report and Release source files

on:
  push:
    branches:
      - main
    paths:
      - 'assignment-01/report/**'
      - 'assignment-02/report/**'
      - 'assignment-03/report/**'
      - 'assignment-04/report/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Hide other LaTeX files from the compiler
        run: |
          find . -type f -name "*.tex" ! -path "./assignment-01/report/*" -delete

      - name: Compile LaTeX
        uses: DanySK/compile-and-publish-all-latex@2.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update release with container images
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_RELEASE=$(gh release list --limit 1 --json tagName -q '.[0].tagName')

          mkdir -p staging/doc staging/src/thread-based staging/src/executor-based 
          cp -r assignment-01/report/* staging/src/
          cp -r assignment-01/thread-based/app/src/main/java/it/unibo/assignment-01/* staging/src/thread-based/      
          cp -r assignment-01/thread-based/app/src/main/java/it/unibo/assignment-01/* staging/src/executor-based/       

          cd staging
          zip -r ../Assignment-01.zip . -x "*.aux" "*.log" "*.out" "*.toc" "*.fls" "*.fdb_latexmk" "*.synctex.gz" "*.bbl" "*.blg" "*.run.xml" "*.bcf"

          gh release upload "$LATEST_RELEASE" Assignment-01.zip
          
          # Get existing body
          EXISTING_BODY=$(gh release view "$LATEST_RELEASE" --json body -q '.body')
          
          # Append container images
          NEW_BODY="
          # Assingment 1: source code and report
          What's new: $EXISTING_BODY
          This release contains everything you need to discuss the project with the professor"
              
          gh release edit "$LATEST_RELEASE" -n "$NEW_BODY"

